### ISSUE TITLE
Write Readme

### ISSUE THREAD

**Issue by guilyx** [MasterERTS/ros2_realtime_statistics#1]
- [x] Links to ROS2
- [x] Links to RT Pendulum Demo
- [x] Goal
- [x] Screenshots
- [ ] ?

**Comment by sampreets3** [comment]
I can take on the initial writing of the README, i.e., the basics for all the topics mentioned above. and we can improve upon that based on guidance from @guilyx

**Comment by guilyx** [comment]
@sampreets3 don't forget one issue one PR ahah
