### ISSUE TITLE
Plot JSON

### ISSUE THREAD

**Issue by guilyx** [MasterERTS/ros2_realtime_statistics#14]
@sampreets3 how is this going ?

**Comment by sampreets3** [comment]
I have been able to plot the data in a tabular format, as shown in the picture below. Just need to figure out the axes and I am done
![Screenshot from 2020-06-12 16-35-23](https://user-images.githubusercontent.com/25011971/84514093-be0b3c00-acca-11ea-81da-0d55313629f5.png)

**Comment by sampreets3** [comment]
Hey @guilyx I am thinking of doing a simple plot where I just show the stats for each key in a plot. Like mean jitter time, how it changes from key 0 to 20. What do you think?

**Comment by sampreets3** [comment]
Hey @guilyx this is the result I have been able to achieve as of now. Working to make this better, by omitting useless data
![Figure_1](https://user-images.githubusercontent.com/25011971/84522242-902bf480-acd6-11ea-96cc-823b71cb64b0.png)

**Comment by guilyx** [comment]
Closed in #15
