### ISSUE TITLE
Change project name

### ISSUE THREAD

**Issue by guilyx** [MasterERTS/ros2_realtime_statistics#2]
- Project : ros2_realtime_statistics
- Packages : 
- [ ] realtime_statistics_json
- [ ] realtime_statistics_plot
- [ ] ?

OR

- Project : ros2_realtime_statistics
- Packages : realtime_statistics
- Nodes :
- [x] write_json
- [x] plot_json

**Comment by sampreets3** [comment]
I think the second option is better because we can introduce both RT and non-RT system characteristics in the same package. Which would be better in the long run

**Comment by guilyx** [comment]
what do you mean ?

**Comment by sampreets3** [comment]
I mean IF we want to develop this further, the main package stack would be ros2_realtime_statistics and inside it we can include support for both RT and Non RT stuff
